A new site block has been added in accordance with the design describ…
petrovsky747/if-html pull request #3
Opened 2022-07-17 07:58 UTC by petrovsky747

…ed in Figma.

To build the html markup of the block used unordered list (in order to simplify the viewing of content for people with disabilities).
A style reset was applied while developing the stylesheet (taken from here https://meyerweb.com/eric/tools/css/reset/).
Classes were defined for each type of objects (the BEM methodology was applied for naming) to customize the display of content on the page.

2022-07-18 19:49 UTC, 5tronciy requested changes
Looks good, but there is no images.

2022-07-18 19:49 UTC, 5tronciy commented on styles/styles.css
> +    /* identical to box height */
Don't commit the useless comments.

2022-07-18 19:49 UTC, 5tronciy commented on styles/styles.css
> +}
You may move the code above to other file, for example reset.css

2022-07-21 19:12 UTC, 5tronciy requested changes
Good in general.
And why you didn't use fonts from the design? Did you ask about it at the weekly meeting?

2022-07-24 06:15 UTC, petrovsky747 commented
> Good in general. And why you didn't use fonts from the design? Did you ask about it at the weekly meeting?

During the 4th lesson, the mentor pointed out that we will go through the fonts in the next lesson and they can not be connected to lesson-4 :)

2022-07-24 16:53 UTC, 5tronciy commented
> > Good in general. And why you didn't use fonts from the design? Did you ask about it at the weekly meeting?
> 
> During the 4th lesson, the mentor pointed out that we will go through the fonts in the next lesson and they can not be connected to lesson-4 :)

Ok, let's do it next time)

2022-07-24 16:53 UTC, merged